--
-- PostgreSQL database dump
--

\restrict M9WCtiqotBRu0VU6oWr5g8e34P6OLWgMOtR5668EaOcEQqTLjtcbcFcwnD4heqn

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-09-23 04:24:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 230 (class 1259 OID 24769)
-- Name: metadata_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metadata_types (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.metadata_types OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 24768)
-- Name: metadata_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.metadata_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.metadata_types_id_seq OWNER TO postgres;

--
-- TOC entry 4882 (class 0 OID 0)
-- Dependencies: 229
-- Name: metadata_types_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.metadata_types_id_seq OWNED BY public.metadata_types.id;


--
-- TOC entry 220 (class 1259 OID 24587)
-- Name: segments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.segments (
    id bigint NOT NULL,
    station_id integer,
    segment_name character varying(255) NOT NULL,
    order_num integer NOT NULL
);


ALTER TABLE public.segments OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24586)
-- Name: segments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.segments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.segments_id_seq OWNER TO postgres;

--
-- TOC entry 4883 (class 0 OID 0)
-- Dependencies: 219
-- Name: segments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.segments_id_seq OWNED BY public.segments.id;


--
-- TOC entry 218 (class 1259 OID 24578)
-- Name: stations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stations (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.stations OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 24577)
-- Name: stations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.stations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.stations_id_seq OWNER TO postgres;

--
-- TOC entry 4884 (class 0 OID 0)
-- Dependencies: 217
-- Name: stations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.stations_id_seq OWNED BY public.stations.id;


--
-- TOC entry 226 (class 1259 OID 24712)
-- Name: tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.tags OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24711)
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tags_id_seq OWNER TO postgres;

--
-- TOC entry 4885 (class 0 OID 0)
-- Dependencies: 225
-- Name: tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tags_id_seq OWNED BY public.tags.id;


--
-- TOC entry 234 (class 1259 OID 24866)
-- Name: title_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.title_metadata (
    id bigint NOT NULL,
    title_id bigint NOT NULL,
    metadata_type_id bigint NOT NULL,
    value jsonb NOT NULL
);


ALTER TABLE public.title_metadata OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 24865)
-- Name: title_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.title_metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.title_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24686)
-- Name: titles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.titles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text
);


ALTER TABLE public.titles OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24685)
-- Name: titles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.titles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.titles_id_seq OWNER TO postgres;

--
-- TOC entry 4886 (class 0 OID 0)
-- Dependencies: 221
-- Name: titles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.titles_id_seq OWNED BY public.titles.id;


--
-- TOC entry 232 (class 1259 OID 24778)
-- Name: video_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.video_metadata (
    id bigint NOT NULL,
    video_id bigint NOT NULL,
    metadata_type_id bigint NOT NULL,
    value jsonb NOT NULL
);


ALTER TABLE public.video_metadata OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 24777)
-- Name: video_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.video_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.video_metadata_id_seq OWNER TO postgres;

--
-- TOC entry 4887 (class 0 OID 0)
-- Dependencies: 231
-- Name: video_metadata_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.video_metadata_id_seq OWNED BY public.video_metadata.id;


--
-- TOC entry 228 (class 1259 OID 24721)
-- Name: video_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.video_tags (
    id bigint NOT NULL,
    video_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.video_tags OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24720)
-- Name: video_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.video_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.video_tags_id_seq OWNER TO postgres;

--
-- TOC entry 4888 (class 0 OID 0)
-- Dependencies: 227
-- Name: video_tags_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.video_tags_id_seq OWNED BY public.video_tags.id;


--
-- TOC entry 224 (class 1259 OID 24696)
-- Name: videos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.videos (
    id bigint NOT NULL,
    title_id bigint NOT NULL,
    uri text NOT NULL
);


ALTER TABLE public.videos OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24695)
-- Name: videos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.videos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.videos_id_seq OWNER TO postgres;

--
-- TOC entry 4889 (class 0 OID 0)
-- Dependencies: 223
-- Name: videos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.videos_id_seq OWNED BY public.videos.id;


--
-- TOC entry 4687 (class 2604 OID 24772)
-- Name: metadata_types id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadata_types ALTER COLUMN id SET DEFAULT nextval('public.metadata_types_id_seq'::regclass);


--
-- TOC entry 4682 (class 2604 OID 24809)
-- Name: segments id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.segments ALTER COLUMN id SET DEFAULT nextval('public.segments_id_seq'::regclass);


--
-- TOC entry 4681 (class 2604 OID 24633)
-- Name: stations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stations ALTER COLUMN id SET DEFAULT nextval('public.stations_id_seq'::regclass);


--
-- TOC entry 4685 (class 2604 OID 24715)
-- Name: tags id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags ALTER COLUMN id SET DEFAULT nextval('public.tags_id_seq'::regclass);


--
-- TOC entry 4683 (class 2604 OID 24689)
-- Name: titles id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles ALTER COLUMN id SET DEFAULT nextval('public.titles_id_seq'::regclass);


--
-- TOC entry 4688 (class 2604 OID 24781)
-- Name: video_metadata id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video_metadata ALTER COLUMN id SET DEFAULT nextval('public.video_metadata_id_seq'::regclass);


--
-- TOC entry 4686 (class 2604 OID 24724)
-- Name: video_tags id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video_tags ALTER COLUMN id SET DEFAULT nextval('public.video_tags_id_seq'::regclass);


--
-- TOC entry 4684 (class 2604 OID 24699)
-- Name: videos id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.videos ALTER COLUMN id SET DEFAULT nextval('public.videos_id_seq'::regclass);


--
-- TOC entry 4713 (class 2606 OID 24776)
-- Name: metadata_types metadata_types_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadata_types
    ADD CONSTRAINT metadata_types_name_key UNIQUE (name);


--
-- TOC entry 4715 (class 2606 OID 24774)
-- Name: metadata_types metadata_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadata_types
    ADD CONSTRAINT metadata_types_pkey PRIMARY KEY (id);


--
-- TOC entry 4695 (class 2606 OID 24811)
-- Name: segments segments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.segments
    ADD CONSTRAINT segments_pkey PRIMARY KEY (id);


--
-- TOC entry 4690 (class 2606 OID 24585)
-- Name: stations stations_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stations
    ADD CONSTRAINT stations_name_key UNIQUE (name);


--
-- TOC entry 4692 (class 2606 OID 24635)
-- Name: stations stations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stations
    ADD CONSTRAINT stations_pkey PRIMARY KEY (id);


--
-- TOC entry 4704 (class 2606 OID 24719)
-- Name: tags tags_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_name_key UNIQUE (name);


--
-- TOC entry 4706 (class 2606 OID 24717)
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- TOC entry 4723 (class 2606 OID 24872)
-- Name: title_metadata title_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.title_metadata
    ADD CONSTRAINT title_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4697 (class 2606 OID 24864)
-- Name: titles titles_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_name_key UNIQUE (name);


--
-- TOC entry 4699 (class 2606 OID 24694)
-- Name: titles titles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.titles
    ADD CONSTRAINT titles_pkey PRIMARY KEY (id);


--
-- TOC entry 4719 (class 2606 OID 24785)
-- Name: video_metadata video_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video_metadata
    ADD CONSTRAINT video_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4709 (class 2606 OID 24726)
-- Name: video_tags video_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video_tags
    ADD CONSTRAINT video_tags_pkey PRIMARY KEY (id);


--
-- TOC entry 4711 (class 2606 OID 24728)
-- Name: video_tags video_tags_video_id_tag_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video_tags
    ADD CONSTRAINT video_tags_video_id_tag_id_key UNIQUE (video_id, tag_id);


--
-- TOC entry 4702 (class 2606 OID 24705)
-- Name: videos videos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.videos
    ADD CONSTRAINT videos_pkey PRIMARY KEY (id);


--
-- TOC entry 4693 (class 1259 OID 24598)
-- Name: idx_segments_station_order; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_segments_station_order ON public.segments USING btree (station_id, order_num);


--
-- TOC entry 4720 (class 1259 OID 24883)
-- Name: idx_title_metadata_title_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_title_metadata_title_id ON public.title_metadata USING btree (title_id);


--
-- TOC entry 4721 (class 1259 OID 24884)
-- Name: idx_title_metadata_value_gin; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_title_metadata_value_gin ON public.title_metadata USING gin (value);


--
-- TOC entry 4716 (class 1259 OID 24802)
-- Name: idx_video_metadata_value_gin; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_video_metadata_value_gin ON public.video_metadata USING gin (value);


--
-- TOC entry 4717 (class 1259 OID 24801)
-- Name: idx_video_metadata_video_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_video_metadata_video_id ON public.video_metadata USING btree (video_id);


--
-- TOC entry 4707 (class 1259 OID 24797)
-- Name: idx_video_tags_video_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_video_tags_video_id ON public.video_tags USING btree (video_id);


--
-- TOC entry 4700 (class 1259 OID 24796)
-- Name: idx_videos_title_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_videos_title_id ON public.videos USING btree (title_id);


--
-- TOC entry 4724 (class 2606 OID 24636)
-- Name: segments segments_station_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.segments
    ADD CONSTRAINT segments_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.stations(id) ON DELETE CASCADE;


--
-- TOC entry 4730 (class 2606 OID 24878)
-- Name: title_metadata title_metadata_metadata_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.title_metadata
    ADD CONSTRAINT title_metadata_metadata_type_id_fkey FOREIGN KEY (metadata_type_id) REFERENCES public.metadata_types(id) ON DELETE CASCADE;


--
-- TOC entry 4731 (class 2606 OID 24873)
-- Name: title_metadata title_metadata_title_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.title_metadata
    ADD CONSTRAINT title_metadata_title_id_fkey FOREIGN KEY (title_id) REFERENCES public.titles(id) ON DELETE CASCADE;


--
-- TOC entry 4728 (class 2606 OID 24791)
-- Name: video_metadata video_metadata_metadata_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video_metadata
    ADD CONSTRAINT video_metadata_metadata_type_id_fkey FOREIGN KEY (metadata_type_id) REFERENCES public.metadata_types(id) ON DELETE CASCADE;


--
-- TOC entry 4729 (class 2606 OID 24786)
-- Name: video_metadata video_metadata_video_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video_metadata
    ADD CONSTRAINT video_metadata_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id) ON DELETE CASCADE;


--
-- TOC entry 4726 (class 2606 OID 24734)
-- Name: video_tags video_tags_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video_tags
    ADD CONSTRAINT video_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;


--
-- TOC entry 4727 (class 2606 OID 24729)
-- Name: video_tags video_tags_video_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.video_tags
    ADD CONSTRAINT video_tags_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id) ON DELETE CASCADE;


--
-- TOC entry 4725 (class 2606 OID 24706)
-- Name: videos videos_title_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.videos
    ADD CONSTRAINT videos_title_id_fkey FOREIGN KEY (title_id) REFERENCES public.titles(id) ON DELETE CASCADE;


-- Completed on 2025-09-23 04:24:07

--
-- PostgreSQL database dump complete
--

\unrestrict M9WCtiqotBRu0VU6oWr5g8e34P6OLWgMOtR5668EaOcEQqTLjtcbcFcwnD4heqn

